// ADD TODOS CONSTANTS
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL'
export const ADD_TODO_RESET = 'ADD_TODO_RESET'

// REMOVE TODO CONSTANTS
export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST'
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS'
export const REMOVE_TODO_FAIL = 'REMOVE_TODO_FAIL'
export const REMOVE_TODO_RESET = 'REMOVE_TODO_RESET'

// UPDATE TODO CONSTANTS
export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
export const UPDATE_TODO_FAIL = 'UPDATE_TODO_FAIL'
export const UPDATE_TODO_RESET = 'UPDATE_TODO_RESET'